### ISSUE TITLE
the objective field

### ISSUE THREAD

**Issue by chihebnabil** [bigmlcom/bigml-php#1]
how i can change  the default objective field?
thanks

**Comment by antoniomachine** [comment]
Hi!
By default, BigML considers the last field in the dataset as the objective field
ok you can do, 

$dataset = $api::create_dataset($source, array('objective_field'=>array("id"=>"000003")));

You can see the fields ids: 
print_r($api::get_fields($source));

More info in https://bigml.com/developers/datasets, objective field...
"default is the last non-autogenerated field in the dataset".   Specifies the default objective field.

Or in a one Model, https://bigml.com/developers/models you can set it too

objective_field
optional    String, default is the id of the last field in the dataset  Specifies the id of the field that you want to predict.
Example: "000003".

You welcome,

T.!
