### ISSUE TITLE
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found

### ISSUE THREAD

**Issue by s1223** [bigmlcom/bigml-php#37]
My Current PHP version: 7.1.28
My PHPUnit 7.5.9 by Sebastian Bergmann and contributors.
PHPUnit installed with PHP Archive (PHAR)
➜ wget -O phpunit https://phar.phpunit.de/phpunit-7.phar
➜ chmod +x phpunit
➜ ./phpunit --version

but after installing PHPUnit with PHAR it isn't generate "src/autoload.php" but just only file phpunit

but if I run ./phpunit --version in terminal it's show PHPUnit 7.5.9 by Sebastian Bergmann and contributors.

I download the zip in https://github.com/bigmlcom/bigml-php and extract it then I run it bigml-php-master/tests/test_00_regressions.php then I got an error message PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found

can anybody help me please

**Comment by mmerce** [comment]
Hi s1223,

sorry about the late response, but v3.0.0 adapted the test suite to be compatible with the new PHP 7.X syntax.

Thanks for the heads up!
